In [3]:
import numpy as np

In [4]:
myList = [10,20,30]
np.array(myList)

array([10, 20, 30])

In [5]:
matrixList =[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrixList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
npArange = np.arange(0,10)
print(npArange)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
myRand = np.random.randn(4,4)
print(myRand)

[[-0.48921338  0.82858421  0.11169628  0.34145909]
 [ 0.69337448 -0.46267975  0.25620407 -1.35964466]
 [ 0.0722197  -1.06279242 -0.61454578 -0.83959271]
 [ 0.60721173 -0.64867708 -1.40724662 -1.26626035]]


In [15]:
myRandom = np.random.randint(0,51,60)
print(myRandom)

[50 14 35 46 15 14 22 43 28 39 32 48 11 18 35 15 31 26 42  5 44 45 42 37
 16 17 18 16 30 42 38  1 43  3  8 15 45  5 24 27 33 24 31  7 25 23 12 25
 47 46 39 17 17 32 50 31 37 38 29 42]


In [17]:
myRandom.reshape(6,10)

array([[50, 14, 35, 46, 15, 14, 22, 43, 28, 39],
       [32, 48, 11, 18, 35, 15, 31, 26, 42,  5],
       [44, 45, 42, 37, 16, 17, 18, 16, 30, 42],
       [38,  1, 43,  3,  8, 15, 45,  5, 24, 27],
       [33, 24, 31,  7, 25, 23, 12, 25, 47, 46],
       [39, 17, 17, 32, 50, 31, 37, 38, 29, 42]])

In [38]:
npArange[0:5] = -3
print(npArange)

[-3 -3 -3 -3 -3  5  6  7  8  9]


In [44]:
myRand[1:,2]

array([ 0.25620407, -0.61454578, -1.40724662])

In [45]:
yeniDizi = np.random.randint(0,101,20)
print(yeniDizi)

[89 14 68 66 43 45 41 36 21 75 39 96 56 82 91 31 28 23 61 43]
